name: flutter_i18n_ahead
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.14
  http: ^1.2.2
  intl: any
  lottie: ^3.1.3
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/images/star_icon.svg
    - assets/images/alternative_star_icon.svg
    - assets/images/background.svg
    - assets/images/logo.svg
    - assets/images/grimorio.png
    - assets/images/more_stars.svg
    - assets/images/grimorio_empty.svg
    - assets/images/grimorio_1152.png
    - assets/images/grimorio_titulo_1152.png
    - assets/images/grimorio_titulo_1152-en.png
    - assets/images/grimorio_titulo_1152-es.png
    - assets/carousel/
    - assets/animations/
    - assets/images/flags/
 
  fonts:
  - family: Bigelow Rules
    fonts:
      - asset: assets/fonts/BigelowRules-Regular.ttf

flutter_native_splash:
  color: "#4D1245"
  image: assets/images/grimorio.png
  android_12:
    color: "#4D1245"
    icon_background_color: "#4D1245"
    image: assets/images/grimorio_1152.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/grimorio.png"
  min_sdk_android: 21